version: '2'
services:
  db:
    container_name: dev_db
    build:
      context: db
    volumes:
      - dev-db-data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    restart: always
    tty: true
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: Asia/Tokyo
  api:
    container_name: dev_api
    build:
      context: api
    privileged: true
    ports:
      - "1323:1323"
    depends_on:
      - db
    volumes:
      - ./api/src:/go/src/github.com/hrkh/tech-dojo-go
    restart: always
    tty: true
volumes:
  dev-db-data:
    driver: local